accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register-info/', views.register_info_view, name='register-info'),
    path('login/', views.login_view, name='login'),
    path('activate-account/', views.activate_account_view, name='activate-account'),
    path('logout/',views.logout_view,name='logout'),
    path('delete-account/', views.delete_account_view, name='delete-account'),
    path('change-password/', views.change_password_view, name='change-password'),
    path('user-panel/', views.user_panel_view, name='user-panel'),
    path('my-profile/', views.my_profile_view, name='my-profile'),
    path('user-profile/@<str:username>/', views.user_profile_view, name='user-profile'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('favorites/', views.favorites_view, name='favorites'),
]

ads/urls.py
from django.urls import path
from . import views

app_name = 'ads'


urlpatterns = [
    path('list/', views.advertise_list_view, name='adv-list'),
    path('detail/<str:adv_slug>/', views.advertise_detail_view, name='adv-detail'),
    path('create/', views.advertise_create_view, name='adv-create'),
    path('attach-images/<str:adv_slug>/', views.advertise_image_create_view, name='attach-images'),
    path('update/<str:adv_slug>/', views.advertise_update_view, name='adv-update'),
]

barters/urls.py
from django.urls import path
from . import views

app_name = 'barters'


urlpatterns = [
    path('list/', views.barter_list_view, name='barter-list'),
    path('detail/<str:barter_slug>/', views.barter_detail_view, name='barter-detail'),
    path('update/<str:barter_slug>/', views.barter_update_view, name='barter-update'),
    path('delete/<str:barter_slug>/', views.barter_delete_view, name='barter-delete'),
    path('create/', views.barter_create_view, name='barter-create'),
    path('create/attach-images/<str:barter_slug>/', views.barter_image_create_view, name='attach-images'),
]

chat/urls.py
from django.urls import path
from . import views

app_name = "chat"


urlpatterns = [
    path('room-list/', views.room_list_view, name='room-list'),
    path('<str:room_name>/', views.chat_room_view, name='chat-room'),
    path('get-create-chat-room/<str:receiver_id>/', views.get_or_create_chat_room_view, name='get-create-chat-room'),
]

digi_kedmat/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


urlpatterns = [
    # ******************************** MVTs ********************************
    path('admin/', admin.site.urls),
    path('', include('generics.urls', namespace='generics')),
    path('auth/',include('accounts.urls', namespace='accounts')),
    path('tahator/',include('barters.urls', namespace='barters')),
    path('ads/', include('ads.urls', namespace='ads')),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('chat/', include('chat.urls', namespace='chat')),
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/global/images/digi-khedmat-favicon.png', permanent=True)),
    
    
    # ******************************** APIs ********************************
    path('api/auth/' , include('accounts.api.urls', namespace='accounts-api')), 
    path('api/barters/', include('barters.api.urls', namespace='barters-api')),
    path('api/ads/', include('ads.api.urls', namespace='ads-api')),
    path('api/jobs/', include('jobs.api.urls', namespace='jobs-api')),
    path('api/chat/', include('chat.api.urls', namespace='chat-api')),

    
    
    # **************************** 3rd Parties *****************************
    path("__reload__/", include("django_browser_reload.urls")),
    # path("__debug__/", include("debug_toolbar.urls")),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^watchman/', include('watchman.urls')),
    path('schema-viewer/', include('schema_viewer.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

handler404 = 'generics.views.handler404'
handler500 = 'generics.views.handler500'
handler403 = 'generics.views.handler403'

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'


urlpatterns = [
    path('list/', views.job_list_view, name='job-list'),
    path('detail/<str:job_slug>/', views.job_detail_view, name='job-detail'), 
    path('create/', views.job_create_view, name='job-create'),
    path('update/<str:job_slug>/', views.job_update_view, name='job-update'),
    path('resume/list/', views.resume_list_view, name='resume-list'),
    path('resume/file-detail/<str:id>/', views.resume_file_detail_view, name='resume-file-detail'),
    path('resume/pdf-download/<str:id>/', views.pdf_download_view, name='pdf-download'),
    path('resume/detail/<str:id>/', views.resume_detail_view, name='resume-detail'),
    path('resume-file-create/<str:job_slug>/', views.resume_file_create_view, name='resume-file-create'),
    path('resume-create/<str:job_slug>/', views.resume_create_view, name='resume-create'),
    path('resume-complete/<str:resume_id>/', views.resume_complete_view, name='resume-complete'),
]

templates/partials/footer.html
<!-- partials/footer.html -->

<footer class="bg-white mt-24">
    <nav class="flex justify-between p-6" aria-label="Global">

        <!-- CopyRight -->
        <div
            style="padding-top: 4px; padding-right: 7px;"
            class="rounded-md shadow-[0_4px_9px_-4px_rgba(59,113,202,0.5)] hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)] focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)]">
            <span style=" padding-top: 2px;">&#169;</span>
            <p style="padding-top: 10px; padding-right: 10px;"
               class="-m-1.5 inline-block px-6 font-vazir">
            دیجی‌خدمت<span>&#8482;</span> تمامی حقوق محفوظ است
            </p>
        </div>
      
        <div class=" rounded-md shadow-[0_4px_9px_-4px_rgba(59,113,202,0.5)] hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)] focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)]"
             role="group">
            <a href="{% url 'generics:about-us' %}" type="button"
                class="px-6 font-vazir"
                data-te-ripple-init data-te-ripple-color="light">
                درباره ما
            </a>
            <a href="{% url 'generics:privacy-policy' %}" type="button"
                class="px-6 font-vazir"
                data-te-ripple-init data-te-ripple-color="light">
                قوانین و سیاست‌ها
            </a>
            <a href="{% url 'generics:certificates' %}" type="button"
                class="px-6 font-vazir"
                data-te-ripple-init data-te-ripple-color="light">
                اعتبارنامه‌ها
            </a>
            <a href="{% url 'generics:contact-us' %}" type="button"
                class="inline-block px-6 pb-2 pt-2.5 font-vazir"
                data-te-ripple-init data-te-ripple-color="light">
                ارتباط با ما
            </a>
        </div>
    </nav>
</footer>

templates/partials/header.html
<!-- partials/header.html -->
{% load static %}

<header class="bg-white">
  <nav class="flex justify-between p-6" aria-label="Global">
      <div style="margin-left: 448px; margin-right: 170px" class="rounded-md shadow-[0_4px_9px_-4px_rgba(59,113,202,0.5)] hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)]"
          role="group">
          <a href="{% url 'generics:main-page' %}" type="button"
              class="inline-block px-6 pt-2 font-vazir"
              data-te-ripple-init data-te-ripple-color="light">
              دیجی‌خدمت
          </a>
          <a href="{% url 'barters:barter-list' %}" type="button"
              class="inline-block px-6 pb-2 pt-2 font-vazir"
              data-te-ripple-init data-te-ripple-color="light">
              تهاتر کالا
          </a>
          <a href="{% url 'ads:adv-list' %}" type="button"
              class="inline-block px-6 pb-2 pt-2 font-vazir"
              data-te-ripple-init data-te-ripple-color="light">
              تبلیغات
          </a>
          <a href="{% url 'jobs:job-list' %}" type="button"
              class="inline-block px-6 pb-2 pt-2 font-vazir"
              data-te-ripple-init data-te-ripple-color="light">
              کاریابی
          </a>
      </div>
      <!-- Start Search Box -->
      <form method="get">
        <div class="shadow-[0_4px_9px_-4px_rgba(59,113,202,0.5)] hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)]">
            <div class="flex rounded-md">
              <!--Search button-->
              <button
              class="border-2 px-6 py-2 rounded-md hover:bg-black hover:bg-opacity-5"
              type="submit" id="button-addon3" data-te-ripple-init>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="h-5 w-5 border-black" >
                <path fill-rule="evenodd"
                d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z"
                clip-rule="evenodd" />
              </svg>
            </button>
            <input 
                name="search-area" 
                value="{{ search_input }}"
                action="{{request.resolver_match.app_name}}/list/" 
                type="text"
                style="border-color: inherit; text-align: center; color: black"
                class="font-vazir leading-[1.6]  placeholder:text-neutral-200 rounded-md"
                maxlength="25"
                placeholder="جستجو"  aria-label="Search" aria-describedby="button-addon3"/>
            </div>
        </div>
      </form>
      <!-- Logo -->
      <div class="rounded-md shadow-[0_4px_9px_-4px_rgba(59,113,202,0.5)] hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)] focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)]">
          <a href="{% url 'generics:main-page' %}" class="-m-1.5 p-1.5 inline-block rounded-l bg-primary px-6 pb-2 pt-2 font-vazir">
              <span class="sr-only">DIGI KHEDMAT</span>
              <img class="h-8" style="margin-bottom: -18px;" src="{% static 'global/images/DigiKhedmatLogo.png' %}" alt="">
          </a>
      </div>
  </nav>
  

</header>

templates/partials/navbar.html
{% load static %}

<!-- partials/navbar.html -->
<nav class="bg-white mt-[-72px]">
  <div class="flex justify-between p-6">
        <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
            {% if request.user.is_authenticated %}
                <!-- Notifications button -->
                <a  href="{% url 'accounts:notifications' %}" class="mt-[-7px] px-6 pb-2 pt-2 bg-white rounded-md
                                                    shadow-[0_4px_9px_-4px_rgba(59,113,202,0.5)]
                                                    hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)]"
                >
                    {% get_notifications_count request as notifications_count %}
                    {% if notifications_count > 0 %}
                        <img src="{% static 'global/icons/notification-available.png' %}" alt="sidebar" class="w-[30px] h-[30px]">
                    {% else %}
                        <img src="{% static 'global/icons/notification.png' %}" alt="sidebar" class="w-[30px] h-[30px]">
                    {% endif %}
                </a>
                
                <!-- Profile dropdown (if needed) -->
                <button id="toggleSidebarBtn" class="mt-[-7px] px-6 pb-2 pt-2 bg-white rounded-md
                                                    shadow-[0_4px_9px_-4px_rgba(59,113,202,0.5)]
                                                    hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)]">
                    <img src="{% static 'global/icons/add-profile-image.png' %}" 
                    alt="sidebar" 
                    class="w-[30px] h-[30px]"
                    >
                </button>

            {% else %}
                <!-- Register and Login buttons (if needed) -->
                <div style="padding-bottom: 6.4px" class="rounded-md shadow-[0_4px_9px_-4px_rgba(59,113,202,0.5)] hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)]"
                    role="group">
                    <a href="{% url 'accounts:register' %}" type="button"
                        class="px-6 pt-2 font-vazir"
                        aria-current="page"
                        data-te-ripple-init data-te-ripple-color="light">
                        ثبت‌نام
                    </a>
                    <a href="{% url 'accounts:login' %}" type="button"
                        class="inline-block px-6 pt-2 font-vazir"
                        aria-current="page"
                        data-te-ripple-init data-te-ripple-color="light">
                        ورود
                    </a>
                </div> 
            {% endif %}
        </div>
    </div>
</nav>

templates/partials/sidebar.html
{% load static %}

<!-- Start siderbar -->
<div id="sidebar" class="font-vazir hidden">
    <div class="fixed flex flex-col top-0 left-0 bg-white h-full" style="width: 18.7rem">
        <div class="flex flex-col items-center">
          <!-- User avatar -->
          <img class="mt-4 w-20 h-20 rounded-full opacity-70"
              src="{% if user.profile_photo %} {{ user.profile_photo.url }} {% else %}  {% static 'global/icons/add-profile-image.png' %} {% endif %}"
              alt="PROFILE"
          />
          <h2 class="text-xl text-gray-600">
            {{ user.username }}
          </h2>
          
        </div>
    <div>
      <ul>
        <li>
          <a href="{% url 'accounts:user-panel' %}" 
            class="flex items-center h-11 hover:bg-gray-50 text-gray-600 hover:text-gray-800 border-l-4 hover:border-indigo-500 pr-6">
                <span class="ml-4">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
                </span>
            <span class="text-sm">
                پنل کاربری
            </span>
          </a>
        </li>
        <li>
          <a href="{% url 'chat:room-list' %}" 
            class="flex items-center h-11 hover:bg-gray-50 text-gray-600 hover:text-gray-800 border-l-4 hover:border-indigo-500 pr-6">
            <span class="ml-4">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z"></path></svg>
            </span>
            <span class="text-sm">پیام‌ها</span>
          </a>
        </li>
        <li>
          <a href="{% url 'accounts:notifications' %}" 
            class="flex items-center h-11 hover:bg-gray-50 text-gray-600 hover:text-gray-800 border-l-4 hover:border-indigo-500 pr-6">
            <span class="ml-4">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"></path></svg>
            </span>
            <span class="ml-2 text-sm">اعلان‌ها</span>
            <span id='unseen-notifications-count' class="px-2 py-0.5 text-xs text-red-500 bg-red-50 rounded-full">
                {{unseen_notifications_count}}
            </span>
          </a>
        </li>
          <div>
            <div class="text-sm text-black">________________________________________________</div>
          </div>
        </li>
        <li>
          <a href="{% url 'accounts:favorites' %}" 
             class="flex items-center h-11 hover:bg-gray-50 text-gray-600 hover:text-gray-800 border-l-4 hover:border-indigo-500 pr-6">
            <span class="ml-4">
              <img class="w-5 h-5" src="{% static 'global/icons/heart.png' %}" alt="favorites">
            </span>
            <span class="ml-2 text-sm">علاقه‌مندی‌ها</span>
            <span id="favorites-count" class="px-2 py-0.5 text-xs text-blue-500 bg-blue-50 rounded-full">
                {{ favorites_count }}
            </span>
          </a>
        </li>
        <li>
          <a href="{% url 'jobs:resume-list' %}" class="flex items-center h-11 hover:bg-gray-50 text-gray-600 hover:text-gray-800 border-l-4 hover:border-indigo-500 pr-6">
            <span class="ml-4">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z"></path></svg>
            </span>
            <span class="ml-2 text-sm">کارجویان</span>
            <span id="resumes-count" class="px-2 py-0.5 ml-auto text-xs font-medium tracking-wide text-green-500 bg-green-50 rounded-full">{{ resumes_count }}</span>
          </a>
        </li>
          <div>
            <div class="text-sm text-black">_____________________________________________________</div>
          </div>
        <li>
          <a href="{{user.get_user_profile}}" 
            class="flex items-center h-11 hover:bg-gray-50 text-gray-600 hover:text-gray-800 border-l-4 hover:border-indigo-500 pr-6">
            <span class="ml-4">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path></svg>
            </span>
            <span class="ml-2 text-sm">حساب کاربری</span>
          </a>
        </li>
        <li>
          <a href="{% url "accounts:my-profile" %}" class="flex items-center h-11 hover:bg-gray-50 text-gray-600 hover:text-gray-800 border-l-4 hover:border-indigo-500 pr-6">
            <span class="ml-4">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"></path>
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
              </svg>
            </span>
            <span class="ml-2 text-sm">تنظیمات حساب</span>
          </a>
        </li>
        <li>
          <a href="{% url 'accounts:logout' %}" 
             class="flex items-center h-11 hover:bg-gray-50 text-gray-600 hover:text-gray-800 border-l-4 hover:border-indigo-500 pr-6">
            <span class="ml-4">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path></svg>
            </span>
            <span class="ml-2 text-sm">
                خروج
            </span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>
<!-- End siderbar -->