accounts/api/urls.py
from django.urls import path
from . import apis


app_name = "accounts_api"


urlpatterns = [
    path('delete-notification/<str:id>/', apis.delete_notification_api, name='delete-notification'),
    path('notification-mark-as-read/<str:id>/',  apis.mark_as_read_api, name='notification-mark-as-read'),
    path('add-favorite/', apis.add_favorite_api, name='add-favorite'),
    path('delete-favorite/<str:id>/', apis.delete_favorite_api, name='delete-favorite'),
    path('send-otp/', apis.send_otp_api, name='send-otp'),
    path('check-field-existence/', apis.check_field_existence_api, name='check-field-existence'),
    path('get-sidebar-counts/', apis.get_sidebar_counts_api, name='get-sidebar-counts'),
    path('get-user-ads-count/<str:username>/', apis.get_user_ads_count_api, name='get-user-ads-count'),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register-info/', views.register_info_view, name='register-info'),
    path('login/', views.login_view, name='login'),
    path('activate-account/', views.activate_account_view, name='activate-account'),
    path('logout/',views.logout_view,name='logout'),
    path('delete-account/', views.delete_account_view, name='delete-account'),
    path('change-password/', views.change_password_view, name='change-password'),
    path('user-panel/', views.user_panel_view, name='user-panel'),
    path('my-profile/', views.my_profile_view, name='my-profile'),
    path('user-profile/@<str:username>/', views.user_profile_view, name='user-profile'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('favorites/', views.favorites_view, name='favorites'),
]

ads/urls.py
from django.urls import path
from . import views

app_name = 'ads'


urlpatterns = [
    path('list/', views.advertise_list_view, name='adv-list'),
    path('detail/<str:adv_slug>/', views.advertise_detail_view, name='adv-detail'),
    path('create/', views.advertise_create_view, name='adv-create'),
    path('attach-images/<str:adv_slug>/', views.advertise_image_create_view, name='attach-images'),
    path('update/<str:adv_slug>/', views.advertise_update_view, name='adv-update'),
]

barters/urls.py
from django.urls import path
from . import views

app_name = 'barters'


urlpatterns = [
    path('list/', views.barter_list_view, name='barter-list'),
    path('detail/<str:barter_slug>/', views.barter_detail_view, name='barter-detail'),
    path('update/<str:barter_slug>/', views.barter_update_view, name='barter-update'),
    path('delete/<str:barter_slug>/', views.barter_delete_view, name='barter-delete'),
    path('create/', views.barter_create_view, name='barter-create'),
    path('create/attach-images/<str:barter_slug>/', views.barter_image_create_view, name='attach-images'),
]

digi_kedmat/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


urlpatterns = [
    # ******************************** MVTs ********************************
    path('admin/', admin.site.urls),
    path('', include('generics.urls', namespace='generics')),
    path('auth/',include('accounts.urls', namespace='accounts')),
    path('tahator/',include('barters.urls', namespace='barters')),
    path('ads/', include('ads.urls', namespace='ads')),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('chat/', include('chat.urls', namespace='chat')),
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/global/images/digi-khedmat-favicon.png', permanent=True)),
    
    
    # ******************************** APIs ********************************
    path('api/auth/' , include('accounts.api.urls', namespace='accounts-api')), 
    path('api/barters/', include('barters.api.urls', namespace='barters-api')),
    path('api/ads/', include('ads.api.urls', namespace='ads-api')),
    path('api/jobs/', include('jobs.api.urls', namespace='jobs-api')),
    path('api/chat/', include('chat.api.urls', namespace='chat-api')),

    
    
    # **************************** 3rd Parties *****************************
    path("__reload__/", include("django_browser_reload.urls")),
    # path("__debug__/", include("debug_toolbar.urls")),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^watchman/', include('watchman.urls')),
    path('schema-viewer/', include('schema_viewer.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

handler404 = 'generics.views.handler404'
handler500 = 'generics.views.handler500'
handler403 = 'generics.views.handler403'

generics/urls.py
from django.urls import path, re_path
from . import views


app_name = 'generics'


urlpatterns = [
    path('', views.main_page_view, name='main-page'),
    path('not-found/', views.handler404, name='not-found'),
    path('server-error/', views.handler500, name='server-error'),
    path('forbidden/', views.handler403, name='forbidden'),
    path('about-us/', views.about_us_view, name='about-us'),
    path('privacy&policy/', views.privacy_policy_view, name='privacy-policy'),
    path('certificates/', views.certificates_view, name='certificates'),
    path('contact-us/', views.contact_us_view, name='contact-us'),
]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'


urlpatterns = [
    path('list/', views.job_list_view, name='job-list'),
    path('detail/<str:job_slug>/', views.job_detail_view, name='job-detail'), 
    path('create/', views.job_create_view, name='job-create'),
    path('update/<str:job_slug>/', views.job_update_view, name='job-update'),
    path('resume/list/', views.resume_list_view, name='resume-list'),
    path('resume/file-detail/<str:id>/', views.resume_file_detail_view, name='resume-file-detail'),
    path('resume/pdf-download/<str:id>/', views.pdf_download_view, name='pdf-download'),
    path('resume/detail/<str:id>/', views.resume_detail_view, name='resume-detail'),
    path('resume-file-create/<str:job_slug>/', views.resume_file_create_view, name='resume-file-create'),
    path('resume-create/<str:job_slug>/', views.resume_create_view, name='resume-create'),
    path('resume-complete/<str:resume_id>/', views.resume_complete_view, name='resume-complete'),
]

accounts/api/views.py
from rest_framework.response import Response
from rest_framework.request import HttpRequest
from rest_framework import authentication as rest_authentications
from rest_framework import permissions as rest_permissions
from rest_framework.decorators import api_view, permission_classes, authentication_classes
from rest_framework import status as rest_status
from .. import models, permissions

def handle_api_response(success_message: str, error_message: str, status_code: int):
    def decorator(func):
        def wrapper(request: HttpRequest, id: str) -> Response:
            try:
                return func(request, id)
            except models.Notification.DoesNotExist:
                return Response(data={"message": "NOT FOUND"}, status=rest_status.HTTP_404_NOT_FOUND)
            except:
                return Response(data={"message": "INTERNAL SERVER ERROR"}, status=rest_status.HTTP_500_INTERNAL_SERVER_ERROR)

        return wrapper

    return decorator

# --------------------------------------------------------------------------------

@api_view(http_method_names=('DELETE',))
@authentication_classes([rest_authentications.SessionAuthentication,])
@permission_classes([permissions.IsNotificationOwnerOrReadOnly,])
@handle_api_response("Notification deleted successfully", "Error deleting notification", rest_status.HTTP_204_NO_CONTENT)
def delete_notification_api(request: HttpRequest, id: str) -> Response:
    if request.method == "DELETE":
        notification = models.Notification.objects.get(id=id)
        notification.delete()
        return Response(status=rest_status.HTTP_204_NO_CONTENT)
    else:
        return Response(data={"message": "BAD REQUEST!"}, status=rest_status.HTTP_400_BAD_REQUEST)

# --------------------------------------------------------------------------------

@api_view(http_method_names=("PATCH",))
@authentication_classes([rest_authentications.SessionAuthentication,])
@permission_classes([permissions.IsNotificationOwnerOrReadOnly,])
@handle_api_response("Notification marked as read successfully", "Error marking notification as read", rest_status.HTTP_204_NO_CONTENT)
def mark_as_read_api(request: HttpRequest, id: str) -> Response:
    if request.method == "PATCH":
        notification = models.Notification.objects.get(id=id)
        notification.toggle_seen()
        return Response(status=rest_status.HTTP_204_NO_CONTENT)
    else:
        return Response(data={"message": "BAD REQUEST!"}, status=rest_status.HTTP_400_BAD_REQUEST)

# --------------------------------------------------------------------------------

@api_view(http_method_names=('DELETE',))
@authentication_classes([rest_authentications.SessionAuthentication,])
@permission_classes([permissions.IsFavoriteOwnerOrReadOnly,])
@handle_api_response("Favorite Object deleted successfully", "Error deleting Favorite Object", rest_status.HTTP_204_NO_CONTENT)
def delete_favorite_api(request: HttpRequest, id: str) -> Response:
    if request.method == "DELETE":
        favorite_obj = models.Favorite.objects.get(id=id)
        favorite_obj.delete()
        return Response(status=rest_status.HTTP_204_NO_CONTENT)
    else:
        return Response(data={"message": "BAD REQUEST!"}, status=rest_status.HTTP_400_BAD_REQUEST)

# --------------------------------------------------------------------------------

from barters.models import BarterAdvertising
from ads.models import Advertise
from jobs.models import JobAdvertising

from django.contrib.contenttypes.models import ContentType

@api_view(http_method_names=('POST',))
@authentication_classes([rest_authentications.SessionAuthentication,])
@permission_classes([permissions.IsFavoriteOwnerOrReadOnly,])
def add_favorite_api(request: HttpRequest) -> Response:
    if request.method == "POST":
        advertisement_id = request.data.get('advertisement_id')
        advertisement_type = request.data.get('advertisement_type')
        
        # Check if the advertisement type is valid
        if advertisement_type not in ['BarterAdvertising', 'Advertise', 'JobAdvertising']:
            return Response(data={"message": "Invalid advertisement type"}, status=rest_status.HTTP_400_BAD_REQUEST)
        
        # Get the ContentType object for the advertisement type
        content_type = ContentType.objects.get(model=advertisement_type.lower())
        
        try:
            # Create a Favorite object
            favorite = models.Favorite.objects.create(
                owner=request.user,
                advertisement_type=content_type,
                object_id=advertisement_id
            )
            return Response(data={"message": "Favorite Object Created successfully"}, status=rest_status.HTTP_201_CREATED)
        except Exception as e:
            return Response(data={"message": str(e)}, status=rest_status.HTTP_500_INTERNAL_SERVER_ERROR)
    else:
        return Response(data={"message": "BAD REQUEST!"}, status=rest_status.HTTP_400_BAD_REQUEST)

templates/accounts/my-profile.html
{% extends "base/base.html" %} 
{% load static %} 

{% block title %}حساب کاربری{% endblock title %} 

{% block content %}
  <div>
    <section class="dark:bg-gray-300 font-vazir">
      <div class="lg:w-1/3 mx-auto lg:py-6">
        <div class="place-items-center">
          <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="flex flex-col items-center">
              <!-- User avatar -->
              <img
                id="profile-image"
                class="mt-4 w-20 h-20 rounded-full dark:opacity-70"
                src="{% if request.user.profile_photo %} {{ request.user.profile_photo.url }} {% else %}  {% static 'global/icons/add-profile-image.png' %} {% endif %}"
                alt="PROFILE"
              />
              <h2 class="text-xl text-gray-600">{{ user.username }}</h2>

              <div class="flex space-x-4 mb-2">
                <a
                  href="{% url 'accounts:change-password' %}"
                  class="relative inline-flex items-center justify-center p-0.5 mx-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-green-400 to-blue-600 group-hover:from-green-400 group-hover:to-blue-600 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800"
                >
                  <span
                    class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0"
                  >
                    تغییر رمز عبور
                  </span>
                </a>

                <a
                  href="{% url 'accounts:register-info' %}"
                  class="relative inline-flex items-center justify-center p-0.5 mx-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-500 to-pink-500 group-hover:from-purple-500 group-hover:to-pink-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-purple-200 dark:focus:ring-purple-800"
                >
                  <span
                    class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0"
                  >
                    تکمیل اطلاعات شما
                  </span>
                </a>

                <a
                  href="{% url 'accounts:delete-account' %}"
                  class="relative inline-flex items-center justify-center p-0.5 mx-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-pink-500 to-orange-400 group-hover:from-pink-500 group-hover:to-orange-400 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800"
                >
                  <span
                    class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0"
                  >
                    حذف حساب کاربری
                  </span>
                </a>
              </div>
            </div>
            <div>
              <label for="photos"> بارگزاری عکس پروفایل جدید: </label>
            </div>
            <div
              class="ml-1 mt-2 flex justify-center rounded-lg border border-dashed border-gray-900"
            >
              <div>
                <div class="mt-4 mr-2 flex text-sm">
                  <label
                    for="file-upload"
                    class="cursor-pointer font-semibold text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-600 focus-within:ring-offset-2 hover:text-indigo-500"
                  >
                    <span> انتخاب عکس </span>
                    <input
                      id="file-upload"
                      name="profile_photo"
                      type="file"
                      class="sr-only"
                      accept=".jpg,.jpeg,.png,"
                    />
                  </label>
                </div>
                <p class="text-xs">PNG, JPG up to 5MB</p>
              </div>
            </div>

            <div>
              <label for="username"> نام کاربری: </label>
              <div class="mt-2">
                <input
                  type="text"
                  name="username"
                  id="username"
                  autocomplete="username"
                  maxlength="25"
                  class="text-center w-full rounded-md py-1.5 placeholder:text-gray-400 sm:text-sm sm:leading-6"
                  placeholder="{{ request.user.username }}"
                  value="{{ request.user.username }}"
                />
              </div>

              <div id="username-errors">
                {% for error in form.username.errors %}
                  <p class="text-red-500 text-xs italic">*{{error}}</p>
                {% endfor %}
              </div>

            </div>
            <div class="mt-6">
              <label for="first_name"> نام: </label>
              <div class="mt-2">
                <input
                  maxlength="20"
                  type="text"
                  name="first_name"
                  id="first_name"
                  autocomplete="family-name"
                  class="text-center w-full rounded-md py-1.5 placeholder:text-gray-400 sm:text-sm sm:leading-6"
                  placeholder="{{ request.user.first_name }}"
                  value="{{ request.user.first_name }}"
                />
              </div>

              <div id="first_name-errors">
                {% for error in form.first_name.errors %}
                  <p class="text-red-500 text-xs italic">*{{error}}</p>
                {% endfor %}
              </div>


            </div>
            <div class="mt-6">
              <label for="last_name"> نام‌خانوادگی: </label>
              <div class="mt-2">
                <input
                  maxlength="20"
                  type="text"
                  name="last_name"
                  id="last_name"
                  autocomplete="family-name"
                  class="text-center w-full rounded-md py-1.5 placeholder:text-gray-400 sm:text-sm sm:leading-6"
                  placeholder="{{ request.user.last_name }}"
                  value="{{ request.user.last_name }}"
                />
              </div>

              <div id="last_name-errors">
                {% for error in form.last_name.errors %}
                  <p class="text-red-500 text-xs italic">*{{error}}</p>
                {% endfor %}
              </div>

            </div>

            <div class="mt-6">
              <label for="phone_number"> شماره تلفن: </label>
              <div class="mt-2">
                <input
                  maxlength="20"
                  type="tel"
                  name="phone_number"
                  id="phone_number"
                  autocomplete="family-name"
                  class="text-center w-full rounded-md py-1.5 placeholder:text-gray-400 sm:text-sm sm:leading-6"
                  placeholder="{{ request.user.phone_number }}"
                  value="{{ request.user.phone_number }}"
                />
              </div>

              <div id="phone_number-errors">
                {% for error in form.phone_number.errors %}
                  <p class="text-red-500 text-xs italic">*{{error}}</p>
                {% endfor %}
              </div>
            </div>

            <div class="mt-6">
              <label for="email"> ایمیل: </label>
              <div class="mt-2">
                <input
                  maxlength="60"
                  type="tel"
                  name="email"
                  id="email"
                  autocomplete="family-name"
                  class="text-center w-full rounded-md py-1.5 placeholder:text-gray-400 sm:text-sm sm:leading-6"
                  placeholder="{{ request.user.email }}"
                  value="{{ request.user.email }}"
                />
              </div>

              <div id="email-errors">
                {% for error in form.email.errors %}
                  <p class="text-red-500 text-xs italic">*{{error}}</p>
                {% endfor %}
              </div>

            </div>

            <button type="submit" class="btn-primary mt-6 w-full">
              ثبت تغییرات
            </button>
          </form>
        </div>
      </div>
    </section>
  </div>
{% endblock content %} 

{% block custom_js %}
  <script >
    const myUsername = '{{request.user.username}}';
    const myPhoneNumber = '{{request.user.phone_number}}';
    const myEmail = '{{request.user.email}}';
    const csrftoken = getCookie('csrftoken');
  </script>
  <script src="{% static 'accounts/js/my-profile.js' %}"></script>
{% endblock custom_js %}

templates/accounts/user-panel.html
{% extends "base/base.html" %}
{% load static %}
{% load humanize %}

{% block title %}پنل کاربری{% endblock title %}



{% block content %}
  <!-- Tabs for small screens -->
  <div class="sm:hidden">
    <label for="tabs" class="sr-only">Select your country</label>
    <select id="tabs" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
        <option>آگهی‌های مبادله کالا</option>
        <option>آگهی‌های کاریابی</option>
        <option>آگهی‌های تبلیغاتی</option>
        <option>Invoice</option>
    </select>
  </div>

  <!-- Content tabs -->
  <div class="font-vazir dark:bg-gray-300 hidden sm:block pb-[335px]">
    <div class="max-w-7xl mx-auto py-8 px-4">
      <div x-data="{showTab: 'barters',}"
        class="bg-white overflow-hidden shadow sm:rounded-lg">
        <div class="border-b border-gray-200 dark:border-gray-700">
          <nav id="tabs" class="-mb-px flex" aria-label="Tabs">
            <a href="#" x-on:click="showTab = 'barters'" :class="{ 'border-b-2 border-blue-500': showTab === 'barters' }" class="w-1/4 py-4 px-1 text-center font-medium text-sm leading-5 text-gray-500 hover:text-gray-700 focus:outline-none focus:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300 dark:focus:text-gray-700" aria-current="page">
              آگهی‌های مبادله کالا
            </a>
            <a href="#" x-on:click="showTab = 'jobs'" :class="{ 'border-b-2 border-blue-500': showTab === 'jobs' }" class="w-1/4 py-4 px-1 text-center font-medium text-sm leading-5 text-gray-500 hover:text-gray-700 focus:outline-none focus:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300 dark:focus:text-gray-700" aria-current="false">آگهی‌های کاریابی</a>
            <a href="#" x-on:click="showTab = 'ads'" :class="{ 'border-b-2 border-blue-500': showTab === 'ads' }" class="w-1/4 py-4 px-1 text-center font-medium text-sm leading-5 text-gray-500 hover:text-gray-700 focus:outline-none focus:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300 dark:focus:text-gray-700" aria-current="false">آگهی‌های تبلیغاتی</a>
            <a href="#" x-on:click="showTab = 'invoice'" :class="{ 'border-b-2 border-blue-500': showTab === 'invoice' }" class="w-1/4 py-4 px-1 text-center font-medium text-sm leading-5 text-gray-500 hover:text-gray-700 focus:outline-none focus:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300 dark:focus:text-gray-700" aria-current="false">سایر</a>
          </nav>
        </div>
        <div>
          <div id="barters" x-show="showTab === 'barters'" class="p-4">
            <!-- Content for barters tab -->
            <div class="mb-8 text-center">
              <a href="{% url 'barters:barter-create' %}" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md transition duration-300 inline-block">
                ساخت آگهی مبادله کالا
              </a>
            </div>
            
            {% if barters %}
              <ul>
                <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 mt-6">
                  {% for barter in barters %}
                    <li class="border-b border-gray-300 py-4" id="{{barter.slug}}">
                      <div class="dark:bg-gray-300 group-hover:opacity-75 lg:aspect-none w-full shadow rounded-lg overflow-hidden">
                        <img src="{{ barter.images.first.image.url }}" class="object-cover h-40 w-full" alt="">
                        <div class="p-6 flex flex-col flex-1">
                          <h3 class="mt-3 mb-2 font-bold text-lg">
                            {{ barter.title }}
                          </h3>
                          <span>
                            معاوضه با : {{ barter.summary }}
                          </span>
                          <div class="flex gap-4 place-content-center mt-auto pt-4 border-t border-slate-950">
                            <span class="text-sm">
                              منطقه: {{ barter.region }}
                            </span>
                            |
                            <span>
                              دسته‌بندی: {% for category in barter.categories.all %} {{category.title}} - {% endfor %}
                            </span>
                          </div>
                        </div>
                        <div class="mr-11">
                          <a href="{{barter.get_absolute_url}}" class="text-blue-500 hover:text-blue-600 mr-2">مشاهده</a>
                          |
                          <a href="{{barter.get_edit_url}}" class="text-blue-500 hover:text-blue-600">ویرایش</a>
                          |
                          <button data-slug="{{barter.slug}}" class="barter-item-delete text-blue-500 hover:text-blue-600 mx-2">حذف</button>
                        </div>
                      </div>
                    </li>
                  {% endfor %}
                </div>
              </ul>
            {% else %}
              <p class="text-lg text-center">
                شما هیچ آگهی‌ مبادله کالایی ندارید.
              </p>
            {% endif %}
          </div>
          
          <div id="jobs" x-show="showTab === 'jobs'" class="p-4 ">
            <!-- Content for jobs tab -->
            <div class="mb-8 text-center">
              <a href="{% url 'jobs:job-create' %}" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md transition duration-300 inline-block">
                ساخت آگهی کاریابی
              </a>
            </div>

            {% if jobs %}
              <ul>
                <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 mt-6">
                  {% for job in jobs %}
                    <li class="border-b border-gray-300 py-4" id="{{job.slug}}">
                      <div class="dark:bg-gray-300 group-hover:opacity-75 lg:aspect-none w-full shadow rounded-lg overflow-hidden">
                        <div class="p-6 flex flex-col flex-1">
                          <h3 class="mt-3 mb-2 font-bold text-lg">
                            {{ job.title }} - 
                            {{ job.summary }}
                          </h3>
                          <div class="mt-auto pt-4 border-t border-slate-950">
                            <p class="text-sm">
                              منطقه: {{ job.region }}
                            </p>
                            <p>همکاری: {% for co_type in job.cooperation_types.all %} {{co_type.name}} - {% endfor %}</p>
                          </div>
                        </div>
                        <div class="mr-11">
                          <a href="{{job.get_absolute_url}}" class="text-blue-500 hover:text-blue-600 mr-2">مشاهده</a>
                          |
                          <a href="{{job.get_edit_url}}" class="text-blue-500 hover:text-blue-600">ویرایش</a>
                          |
                          <button data-slug="{{job.slug}}" class="job-item-delete text-blue-500 hover:text-blue-600 mx-2">حذف</button>
                        </div>
                      </div>
                    </li>
                  {% endfor %}
                </div>
              </ul>
            {% else %}
              <p class="text-lg text-center">شما هیچ آگهی کاریابی ندارید.</p>
            {% endif %}
          </div>
          
          <div id="ads" x-show="showTab === 'ads'" class="p-4">
            <!-- Content for ads tab -->
            <div class="mb-8 text-center">
              <a href="{% url 'ads:adv-create' %}" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md transition duration-300 inline-block">
                ساخت آگهی تبلیغاتی
              </a>
            </div>
            
            {% if stuff_ads %}
              <ul>
                <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 mt-6">
                  {% for stuff_adv in stuff_ads %}
                    <li class="border-b border-gray-300 py-4" id="{{stuff_adv.slug}}">
                      <div class="dark:bg-gray-300 group-hover:opacity-75 lg:aspect-none w-full shadow rounded-lg overflow-hidden">
                        <img src="{{ stuff_adv.images.first.image.url }}" class="object-cover h-40 w-full" alt="">
                        <div class="p-6 flex flex-col flex-1">
                          <h3 class="mt-3 mb-2 font-bold text-lg">
                            {{ stuff_adv.title }} - 
                            {{ stuff_adv.summary }}
                          </h3>
                          <div class="flex gap-4 place-content-center mt-auto pt-4 border-t border-slate-950">
                            <span class="text-sm">
                              وضعیت آگهی: {{ stuff_adv.get_stuff_status }}
                            </span>
                            |
                            <span class="text-sm">
                              {{ stuff_adv.price | intcomma }} تومان
                            </span>
                          </div>
                        </div>
                        <div class="mr-11">
                          <a href="{{stuff_adv.get_absolute_url}}" class="text-blue-500 hover:text-blue-600 mr-2">مشاهده</a>
                          |
                          <a href="{{stuff_adv.get_edit_url}}" class="text-blue-500 hover:text-blue-600">ویرایش</a>
                          |
                          <button  data-slug="{{stuff_adv.slug}}" class="stuff_adv-item-delete text-blue-500 hover:text-blue-600 mx-2">حذف</button>
                        </div>
                      </div>
                    </li>
                  {% endfor %}
                </div>
              </ul>
            {% else %}
              <p class="text-lg text-center">
                شما هیچ آگهی تبلیغاتی ندارید.
              </p>
            {% endif %}
          </div>
          
          <div id="invoice" x-show="showTab === 'invoice'" class="p-4">
            <!-- Content for invoice tab -->
            <p>به زودی...</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}


{% block custom_js %}
  <script src="{% static 'accounts/js/user-panel.js' %}"></script>
{% endblock custom_js %}