accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register-info/', views.register_info_view, name='register-info'),
    path('login/', views.login_view, name='login'),
    path('activate-account/', views.activate_account_view, name='activate-account'),
    path('logout/',views.logout_view,name='logout'),
    path('delete-account/', views.delete_account_view, name='delete-account'),
    path('change-password/', views.change_password_view, name='change-password'),
    path('user-panel/', views.user_panel_view, name='user-panel'),
    path('my-profile/', views.my_profile_view, name='my-profile'),
    path('user-profile/@<str:username>/', views.user_profile_view, name='user-profile'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('favorites/', views.favorites_view, name='favorites'),
]

ads/urls.py
from django.urls import path
from . import views

app_name = 'ads'


urlpatterns = [
    path('list/', views.advertise_list_view, name='adv-list'),
    path('detail/<str:adv_slug>/', views.advertise_detail_view, name='adv-detail'),
    path('create/', views.advertise_create_view, name='adv-create'),
    path('attach-images/<str:adv_slug>/', views.advertise_image_create_view, name='attach-images'),
    path('update/<str:adv_slug>/', views.advertise_update_view, name='adv-update'),
]

chat/api/urls.py
from django.urls import path
from . import apis

app_name = "chat_api"


urlpatterns = [
    path('room-delete/<str:name>/', apis.room_delete_api, name='room-delete'),
    path('room-report/<str:name>/', apis.room_report_api, name='room-report'),
]

chat/urls.py
from django.urls import path
from . import views

app_name = "chat"


urlpatterns = [
    path('room-list/', views.room_list_view, name='room-list'),
    path('<str:room_name>/', views.chat_room_view, name='chat-room'),
    path('get-create-chat-room/<str:receiver_id>/', views.get_or_create_chat_room_view, name='get-create-chat-room'),
]

digi_kedmat/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


urlpatterns = [
    # ******************************** MVTs ********************************
    path('admin/', admin.site.urls),
    path('', include('generics.urls', namespace='generics')),
    path('auth/',include('accounts.urls', namespace='accounts')),
    path('tahator/',include('barters.urls', namespace='barters')),
    path('ads/', include('ads.urls', namespace='ads')),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('chat/', include('chat.urls', namespace='chat')),
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/global/images/digi-khedmat-favicon.png', permanent=True)),
    
    
    # ******************************** APIs ********************************
    path('api/auth/' , include('accounts.api.urls', namespace='accounts-api')), 
    path('api/barters/', include('barters.api.urls', namespace='barters-api')),
    path('api/ads/', include('ads.api.urls', namespace='ads-api')),
    path('api/jobs/', include('jobs.api.urls', namespace='jobs-api')),
    path('api/chat/', include('chat.api.urls', namespace='chat-api')),

    
    
    # **************************** 3rd Parties *****************************
    path("__reload__/", include("django_browser_reload.urls")),
    # path("__debug__/", include("debug_toolbar.urls")),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^watchman/', include('watchman.urls')),
    path('schema-viewer/', include('schema_viewer.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

handler404 = 'generics.views.handler404'
handler500 = 'generics.views.handler500'
handler403 = 'generics.views.handler403'

chat/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
import uuid


class Thread(models.Model):
    name = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # -------------------------------------------------
    user1 = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='my_threads')
    # -------------------------------------------------
    user2 = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='others_threads')
    # -------------------------------------------------

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user1', 'user2'], name='unique_chat_thread'),
        ]

    # -------------------------------------------------

    def __str__(self):
        return f"Chat between {self.user1} and {self.user2}"
    
    # -------------------------------------------------
    
    def get_room_url(self):
        return reverse('chat:chat-room', kwargs={'room_name': self.name})

# =====================================================================

class Message(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # -------------------------------------------------
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE, related_name='messages')
    # -------------------------------------------------
    from_user = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING, related_name='sent_messages')
    # -------------------------------------------------
    to_user = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING, related_name='received_messages')
    # -------------------------------------------------
    content = models.CharField(max_length=255, blank=True, null=True)
    # -------------------------------------------------
    created_at = models.DateTimeField(auto_now_add=True)
    # -------------------------------------------------

    def __str__(self):
        return f"Message from {self.from_user} to {self.to_user}"

    
# =====================================================================

class Report(models.Model):
    thread = models.ForeignKey(to=Thread, on_delete=models.SET_NULL, null=True, blank=True, related_name='reports', verbose_name="کفت و گو")
    # -------------------------------------------------
    reporter = models.ForeignKey(to=get_user_model(), on_delete=models.SET_NULL, null=True, related_name='reports', verbose_name="گزارش دهنده")
    # -------------------------------------------------
    message = models.TextField(max_length=400, verbose_name="پیام گزارش")
    # -------------------------------------------------
    date_reported = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ گزارش")
    

chat/views.py
import uuid
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from django.db.models import Q
from accounts.models import Account
from . import models, decorators


@login_required(login_url='accounts:login')
def get_or_create_chat_room_view(request: HttpRequest, receiver_id: str) -> HttpResponseRedirect:
    receiver = get_object_or_404(Account, id=receiver_id)
    
    if  request.user == receiver:
        return redirect('generics:main-page')

    threads = models.Thread.objects.filter((Q(user1=request.user) &  Q(user2=receiver)) | (Q(user1=receiver) & Q(user2=request.user)))
    if threads.exists():
        thread = threads.first()
    else:
        thread = models.Thread.objects.create(user1=request.user, user2=receiver)
    
        
    return redirect(thread.get_room_url())
    
# --------------------------------------------------------------

@login_required(login_url='accounts:login')
@decorators.member_required
def chat_room_view(request: HttpRequest, room_name: str) -> HttpResponse:
    # Retrieve the thread or return a 404 response
    thread = get_object_or_404(models.Thread, name=room_name)
    
    sender = request.user
    receiver = thread.user1 if thread.user2 == sender else thread.user2

    # Retrieve room messages ordered by created_at
    room_messages = thread.messages.all().order_by('created_at')

    context = {
        'room_name': thread.name,
        'room_messages': room_messages,
        'sender': sender,
        'receiver': receiver,
    }
    return render(request, 'chat/chat-room.html', context)

# --------------------------------------------------------------

@login_required(login_url='accounts:login')
def room_list_view(request: HttpRequest) -> HttpResponse:
    user = request.user    
    rooms = models.Thread.objects.filter(Q(user1=user) | Q(user2=user)).distinct()
            
    context = {
        'rooms': rooms,
    }
    
    return render(request, 'chat/room-list.html', context)

# --------------------------------------------------------------

templates/chat/chat-room.html
{% extends "base/base.html" %} 
{% load static %} 

{% block title %}دیجی خدمت{% endblock title %} 

{% block content %}
  <div
    id="messages"
    class="font-vazir flex flex-col items-center justify-center w-screen min-h-[80vh] bg-gray-100 text-gray-800 p-10"
  >
    <div
      class="flex items-center space-x-2 w-full max-w-xl bg-gray-900 rounded-lg p-4"
    >
      <img
        src="{% if receiver.profile_photo %} {{receiver.profile_photo.url}} {% else %} {% static 'global/icons/add-profile-image.png' %} {% endif %}"
        class="h-10 w-10 rounded-full bg-white"
        alt="{{ receiver.username }}"
      />
      <div class="pr-2 text-xl font-bold text-white">
        <div>
          {{ receiver.username }}
        </div>
        <a
          href="{{receiver.get_user_profile}}"
          class="text-sm text-gray-500 dark:text-gray-400">
          مشاهده مشخصات
        </a>
      </div>
    </div>

    <div
      class="flex flex-col flex-grow w-full max-w-xl bg-white shadow-xl rounded-lg overflow-hidden mt-4"
    >
      <div
        id="message-list"
        class="flex flex-col flex-grow h-0 p-4 overflow-auto"
      >
        {% for message in room_messages %} 
          {% if request.user == message.from_user %}
            <div class="flex w-full mt-2 space-x-3 max-w-full justify-start">
              <div class="flex-shrink-0 h-10 w-10 rounded-full">
                <img
                  src="{% if sender.profile_photo %} {{sender.profile_photo.url}} {% else %} {% static 'global/icons/add-profile-image.png' %} {% endif %}"
                  class="flex-shrink-0 h-10 w-10 rounded-full"
                  alt="O"
                />
              </div>
              <div class="bg-gray-200 p-3 rounded-lg text-right">
                <p class="text-sm text-gray-800">{{ message.content }}</p>
                <span class="text-xs text-gray-500 leading-none"
                  >{{ message.created_at | to_Jdatetime }}</span
                >
              </div>
            </div>
          {% else %}
            <div class="flex w-full mt-2 space-x-3 max-w-full justify-end">
              <div class="bg-blue-600 text-white p-3 rounded-lg text-left">
                <p class="text-sm">{{ message.content }}</p>
                <span class="text-xs text-gray-300 leading-none"
                  >{{ message.created_at | to_Jdatetime }}</span
                >
              </div>
              <div class="flex-shrink-0 h-10 w-10 rounded-full">
                <img
                  src="{% if receiver.profile_photo %} {{receiver.profile_photo.url}} {% else %} {% static 'global/icons/add-profile-image.png' %} {% endif %}"
                  class="flex-shrink-0 h-10 w-10 rounded-full"
                  alt="O"
                />
              </div>
            </div>
          {% endif %} 
        {% endfor %}
      </div>

      <form action="" id="message-form" class="flex items-center p-4">
        {% csrf_token %}
        <input
          type="text"
          id="id_message"
          name="message"
          maxlength="100"
          placeholder="پیام خود را وارد کنید..."
          required
          class="flex-1 border p-2 mr-2 rounded-lg focus:outline-none focus:border-indigo-300 h-12"
        />
        <button
          type="submit"
          class="bg-blue-500 mx-1 text-white px-4 py-2 rounded-lg hover:bg-blue-600 transition-all"
        >
          ارسال
          <i class="fas fa-paper-plane"></i>
        </button>
      </form>
    </div>
  </div>
{% endblock content %} 


{% block custom_js %}
  <!-- script for defining and using django variables in js file -->
  <script>
    const roomName = "{{ room_name }}";
    const senderUsername = "{{sender.username}}";
    const senderProfilePhoto =
      "{% if sender.profile_photo %} {{sender.profile_photo.url}} {% else %} {% static 'global/icons/add-profile-image.png' %} {% endif %}";
    const receiverUsername = "{{receiver.username}}";
    const receiverProfilePhoto =
      "{% if receiver.profile_photo %} {{receiver.profile_photo.url}} {% else %} {% static 'global/icons/add-profile-image.png' %} {% endif %}";
    const currentUser = "{{request.user.id}}";
  </script>

  <script src="{% static 'chat/js/chat.js' %}"></script>
{% endblock custom_js %}

templates/chat/room-list.html
{% extends "base/base.html" %} 
{% load static %} 
{% load chat_tags %} 

{% block title %}پیام‌ها{% endblock title %} 

{% block content %}

<!--
Include Tailwind JIT CDN compiler
More info: https://beyondco.de/blog/tailwind-jit-compiler-via-cdn
-->
<script src="https://unpkg.com/tailwindcss-jit-cdn"></script>

<!-- Specify a custom Tailwind configuration -->


<!-- Snippet -->
<section class="font-vazir flex flex-col justify-center antialiased bg-gray-50 text-gray-600 min-h-screen p-4">
  <div class="h-full">
      <h3 class="text-2xl font-semibold text-gray-900 dark:text-white text-center">
        پیام‌های شما
      </h3>
        <!-- Card -->
        <div class="relative max-w-[340px] mx-auto bg-white shadow-lg rounded-lg">
            <!-- Card header -->
            <header class="pt-6 pb-4 px-5 border-b border-gray-200">
                <div class="flex justify-between items-center mb-3">
                    <!-- Image + name -->
                    <div class="flex items-center">
                        <a class="inline-flex items-start mr-3">
                            <img class="rounded-full" src="{% if user.profile_photo %} {{user.profile_photo.url}} {% else %} {% static 'global/icons/add-profile-image.png' %} {% endif %}" width="48" height="48" alt="Lauren Marsano" />
                        </a>
                        <div class="pr-1">
                            <a class="inline-flex text-gray-800 hover:text-gray-900">
                                <h2 class="text-xl leading-snug font-bold">
                                  {{ user.get_full_name }}
                                </h2>
                            </a>
                            <a class="block text-sm font-medium hover:text-indigo-500" href="{{user.get_user_profile}}">
                              {{ user.get_username }}@
                            </a>
                        </div>
                    </div>
                    <!-- Settings button -->
                    <a href="{% url "accounts:my-profile" %}">
                      <div class="relative inline-flex flex-shrink-0">
                          <button class="text-gray-400 hover:text-gray-500 rounded-full focus:ring-0 outline-none focus:outline-none">
                              <span class="sr-only">Settings</span>
                              <svg class="w-4 h-4 fill-current" viewBox="0 0 16 16">
                                  <path d="m15.621 7.015-1.8-.451A5.992 5.992 0 0 0 13.13 4.9l.956-1.593a.5.5 0 0 0-.075-.611l-.711-.707a.5.5 0 0 0-.611-.075L11.1 2.87a5.99 5.99 0 0 0-1.664-.69L8.985.379A.5.5 0 0 0 8.5 0h-1a.5.5 0 0 0-.485.379l-.451 1.8A5.992 5.992 0 0 0 4.9 2.87l-1.593-.956a.5.5 0 0 0-.611.075l-.707.711a.5.5 0 0 0-.075.611L2.87 4.9a5.99 5.99 0 0 0-.69 1.664l-1.8.451A.5.5 0 0 0 0 7.5v1a.5.5 0 0 0 .379.485l1.8.451c.145.586.378 1.147.691 1.664l-.956 1.593a.5.5 0 0 0 .075.611l.707.707a.5.5 0 0 0 .611.075L4.9 13.13a5.99 5.99 0 0 0 1.664.69l.451 1.8A.5.5 0 0 0 7.5 16h1a.5.5 0 0 0 .485-.379l.451-1.8a5.99 5.99 0 0 0 1.664-.69l1.593.956a.5.5 0 0 0 .611-.075l.707-.707a.5.5 0 0 0 .075-.611L13.13 11.1a5.99 5.99 0 0 0 .69-1.664l1.8-.451A.5.5 0 0 0 16 8.5v-1a.5.5 0 0 0-.379-.485ZM8 11a3 3 0 1 1 0-6 3 3 0 0 1 0 6Z" />
                              </svg>
                          </button>
                      </div>
                    </a>
                </div>
            </header>
            <!-- Card body -->
            <div class="py-3 px-5">
                <h3 class="text-xs font-semibold uppercase text-gray-800 mb-1">
                  پیام‌ها
                </h3>
                <!-- Chat list -->
                {% comment %} <div class="divide-y divide-gray-200">
                    <!-- User -->
                    <button class="w-full text-left py-2 focus:outline-none focus-visible:bg-indigo-50">
                        <div class="flex items-center">
                            <img class="rounded-full items-start flex-shrink-0 mr-3" src="https://res.cloudinary.com/dc6deairt/image/upload/v1638102932/user-32-01_pfck4u.jpg" width="32" height="32" alt="Marie Zulfikar" />
                            <div>
                                <h4 class="text-sm font-semibold text-gray-900">Marie Zulfikar</h4>
                                <div class="text-[13px]">The video chat ended · 2hrs</div>
                            </div>
                        </div>
                    </button>
                    <!-- User -->
                </div> {% endcomment %}
                <ul class="max-w-md space-y-4">
  {% for room in rooms %} {% get_other_user request.user room as other_user %}
  <li
    id="room-{{ room.name }}"
    class="bg-white shadow-md rounded-md overflow-hidden"
  >
    <div x-data="{ isOpen: false, action: '' }">
      <!-- Button to toggle menu -->
      <button
        @click="isOpen = !isOpen"
        class="inline-flex items-center p-2 text-sm font-medium text-center text-gray-900 bg-white rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none dark:text-white focus:ring-gray-50 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
        type="button"
      >
        <svg
          class="w-5 h-5"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="currentColor"
          viewBox="0 0 16 3"
        >
          <path
            d="M2 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm6.041 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM14 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Z"
          />
        </svg>
      </button>

      <!-- Dropdown menu -->
      <div
        class="z-10 bg-white divide-y divide-gray-100 rounded-lg shadow w-32 dark:bg-gray-700 dark:divide-gray-600"
        x-show="isOpen"
        @click.away="isOpen = false"
      >
        <ul
          class="py-2 text-sm text-gray-700 dark:text-gray-200"
          aria-labelledby="dropdownMenuIconHorizontalButton"
        >
            <button
              @click="action = 'delete'"
              class="mr-1 delete-room px-3 py-2 text-xs font-medium text-center text-white bg-red-700 rounded-lg hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800"
              data-room-name="{{ room.name }}"
            >
              حذف
            </button>
            <button
              @click="action = 'report'"
              class="mr-3 report-room px-3 py-2 text-xs font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
              data-room-name="{{ room.name }}"
            >
              گزارش
            </button>
        </ul>
      </div>
    </div>

    <a
      href="{{ room.get_room_url }}"
      class="block hover:bg-gray-100 dark:hover:bg-gray-800 transition duration-300"
    >
      <div class="flex items-center p-4">
        <img
          src="{% if other_user.profile_photo %} {{ other_user.profile_photo.url }} {% else %} {% static 'global/icons/user.png' %} {% endif %}"
          class="w-12 h-12 rounded-full"
          alt="Other user"
        />
        <div class="ml-4">
          <p class="text-lg font-semibold text-gray-900 dark:text-white">
            {{ other_user.username }}
          </p>
          <p class="text-sm text-gray-500 dark:text-gray-400 mr-4">
            {% if room.messages.count %}
            <span class="block">{{ room.messages.last.content }}</span>
            <span class="text-gray-400"
              >{{ room.messages.last.created_at | to_Jdatetime }}</span
            >
            {% else %}
            <span class="text-gray-400">-</span>
            {% endif %}
          </p>
        </div>
      </div>
    </a>
  </li>
  {% endfor %}
</ul>

<!-- start modal for taking report -->
<div id="reportModal" class="fixed inset-0 z-10 overflow-y-auto hidden">
  <div class="flex items-center justify-center min-h-screen">
    <div class="fixed inset-0 bg-black opacity-50"></div>
    <div class="relative bg-white rounded-lg max-w-lg p-6">
      <div class="flex justify-between items-center mb-4">
        <h5 class="text-lg font-semibold">گزارش گفتگو</h5>
        <button
          type="button"
          id="modal-close"
          class="text-gray-500 hover:text-gray-700 focus:outline-none"
        >
          <svg
            class="w-6 h-6"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M6 18L18 6M6 6l12 12"
            ></path>
          </svg>
        </button>
      </div>
      <div class="mb-4">
        <input type="hidden" id="reportRoomName" />
        <label
          for="reportMessage"
          class="block text-sm font-medium text-gray-700"
          >پیام گزارش:</label
        >
        <textarea
          id="reportMessage"
          rows="3"
          required
          maxlength="400"
          minlength="1"
          class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-300 focus:ring focus:ring-blue-200 focus:ring-opacity-50"
        ></textarea>
      </div>
      <div class="flex justify-end">
        <button
          type="button"
          id="submit-btn"
          class="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 focus:outline-none focus:bg-blue-600"
        >
          ارسال گزارش
        </button>
        <button
          type="button"
          id="cancel-btn"
          class="ml-2 px-4 py-2 bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300 focus:outline-none focus:bg-gray-300"
        >
          لغو
        </button>
      </div>
    </div>
  </div>
</div>
            </div>
        </div>
    </div>
</section>




<!-- end modal for taking report --> 

{% endblock content %} 

{% block custom_js %}
  <script src="{% static 'chat/js/room-list.js' %}"></script>
{% endblock custom_js %}