ads/api/urls.py
from django.urls import path
from . import apis


app_name = "ads-api"


urlpatterns = [
    path('stuff-adv-delete/<str:adv_slug>/', apis.stuff_adv_delete_api, name='stuff-ads-delete'),
    path('stuff-adv-image-delete/<int:id>/', apis.stuff_image_delete_api, name='stuff-image-delete'),
    path('adv-fetch-views/<str:adv_slug>/', apis.advertise_fetch_views_api, name='adv-fetch-views'),
]

ads/urls.py
from django.urls import path
from . import views

app_name = 'ads'


urlpatterns = [
    path('list/', views.advertise_list_view, name='adv-list'),
    path('detail/<str:adv_slug>/', views.advertise_detail_view, name='adv-detail'),
    path('create/', views.advertise_create_view, name='adv-create'),
    path('attach-images/<str:adv_slug>/', views.advertise_image_create_view, name='attach-images'),
    path('update/<str:adv_slug>/', views.advertise_update_view, name='adv-update'),
]

digi_kedmat/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


urlpatterns = [
    # ******************************** MVTs ********************************
    path('admin/', admin.site.urls),
    path('', include('generics.urls', namespace='generics')),
    path('auth/',include('accounts.urls', namespace='accounts')),
    path('tahator/',include('barters.urls', namespace='barters')),
    path('ads/', include('ads.urls', namespace='ads')),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('chat/', include('chat.urls', namespace='chat')),
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/global/images/digi-khedmat-favicon.png', permanent=True)),
    
    
    # ******************************** APIs ********************************
    path('api/auth/' , include('accounts.api.urls', namespace='accounts-api')), 
    path('api/barters/', include('barters.api.urls', namespace='barters-api')),
    path('api/ads/', include('ads.api.urls', namespace='ads-api')),
    path('api/jobs/', include('jobs.api.urls', namespace='jobs-api')),
    path('api/chat/', include('chat.api.urls', namespace='chat-api')),

    
    
    # **************************** 3rd Parties *****************************
    path("__reload__/", include("django_browser_reload.urls")),
    # path("__debug__/", include("debug_toolbar.urls")),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^watchman/', include('watchman.urls')),
    path('schema-viewer/', include('schema_viewer.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

handler404 = 'generics.views.handler404'
handler500 = 'generics.views.handler500'
handler403 = 'generics.views.handler403'

ads/models.py
import uuid
import pathlib
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.db import models
from generics import models as generics_models
from accounts import models as accounts_models


class StuffAdvertising(generics_models.BaseAdvertisingModel):
    STUFF_STATUSES = (
        ('unknown', "نامشخص"),
        ('new', "نو"),
        ('semi-new', "در حد نو"),
        ('used', "کارکرده"),
        ('defective', "معیوب"),
    )
    # --------------------------------------------------------------------------
    owner = models.ForeignKey(to=get_user_model(), on_delete=models.CASCADE, related_name='stuff_ads', null=True, blank=True, verbose_name="مالک")
    # --------------------------------------------------------------------------
    stuff_status = models.CharField(max_length=12, default='unknown', choices=STUFF_STATUSES, verbose_name="وضعیت کالا")
    # --------------------------------------------------------------------------
    price = models.CharField(max_length=20, null=True, default="رایگان" , verbose_name="قیمت")
    # --------------------------------------------------------------------------
    region  = models.ForeignKey(to=generics_models.Region, on_delete=models.SET_NULL, null=True, blank=True, related_name='stuffs', verbose_name="منطقه")
    # --------------------------------------
    categories = models.ManyToManyField(to=generics_models.StuffCategory, blank=True, related_name='stuff_ads', verbose_name="دسته بندی")
    # --------------------------------------
    tags = models.ManyToManyField(generics_models.Tag, blank=True, related_name='stuff_ads', verbose_name="تگ")
    # --------------------------------------
    address = models.CharField(max_length=75, null=True, blank=True, verbose_name="آدرس")
    
    class Meta:
        pass
    
    # --------------------------------------------------------------------------
    
    def __str__(self) -> str:
        return f"{self.title}"
    
    # --------------------------------------------------------------------------
    
    def get_absolute_url(self):
        return reverse("ads:adv-detail", kwargs={"adv_slug": self.slug})
    
    # --------------------------------------------------------------------------
    
    def get_edit_url(self):
        return reverse("ads:adv-update", kwargs={"adv_slug": self.slug})
    
    # --------------------------------------------------------------------------
    
    def update_categories(self, categories):
        self.categories.set(categories)
        super().save()
    
    # --------------------------------------------------------------------------
    
    def update_tags(self, tags):
        self.tags.set(tags)
        super().save()
    
    # --------------------------------------------------------------------------

    def get_stuff_status(self):
        # Iterate over STUFF_STATUSES to find the label for the current stuff status
        for status in self.STUFF_STATUSES:
            if status[0] == self.stuff_status:
                return status[1]
        return '-'  # Return an empty string if the type is not found

    # --------------------------------------------------------------------------
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.slug = f"{self.id}-{slugify(value=self.title, allow_unicode=True)}"
        super().save(*args, **kwargs)
    
    # --------------------------------------------------------------------------

# ==============================================================
    
class StuffImage(models.Model):
    def stuff_image_path(instance, filename):
        file_path = pathlib.Path(filename)
        new_filename = str(uuid.uuid1())
        return f"ads/stuffs/imgs/{new_filename}{file_path.suffix}"
    
    title = models.CharField(max_length=40, null=True, blank=True, verbose_name="عنوان")
    image = models.ImageField(max_length=255, upload_to=stuff_image_path, verbose_name="تصویر")
    stuff_advertising = models.ForeignKey(StuffAdvertising, on_delete=models.CASCADE, related_name='images', verbose_name="تبلیغات کالا")

    def __str__(self):
        return f"{self.id}>{self.title}"

# ==============================================================

class BusinessAdvertising(models.Model):
    BUSINESS_TYPES = (
        ('unknown', "نامشخص"),
        ('offline', "آفلاین"),
        ('online', "آنلاین"),
        ('hybrid', "ترکیبی"),
    )
    # ----------------------------------------------------------
    id    = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # ----------------------------------------------------------
    business_type = models.CharField(max_length=10, choices=BUSINESS_TYPES, default="unknown" ,verbose_name="نوع کسب و کار")
    # ----------------------------------------------------------
    name = models.CharField(max_length=100, verbose_name="نام کسب و کار")
    # ----------------------------------------------------------
    web_address = models.CharField(max_length=200, null=True, blank=True, verbose_name="آدرس وبسایت")
    # ----------------------------------------------------------
    social_networks = models.ManyToManyField(to=generics_models.SocialNetwork, blank=True, verbose_name="شبکه های اجتماعی")
    # ----------------------------------------------------------
    business_address = models.CharField(max_length=300, null=True, blank=True, verbose_name="آدرس کسب و کار")
    # ----------------------------------------------------------
    description = models.TextField(max_length=800, null=True, blank=True, verbose_name="توضیحات")
    # ----------------------------------------------------------
    phone_number = models.CharField(max_length=20, null=True, blank=True, verbose_name="تلفن")
    # ----------------------------------------------------------
    region  = models.ForeignKey(to=generics_models.Region, on_delete=models.SET_NULL, null=True, blank=True, related_name='businesses', verbose_name="منطقه")
    # --------------------------------------
    address = models.CharField(max_length=255, null=True, blank=True, verbose_name="آدرس")
    
    
    class Meta:
        pass
    

# ==============================================================

class BusinessImage(models.Model):
    def business_image_path(instance, filename):
        file_path = pathlib.Path(filename)
        new_filename = str(uuid.uuid1())
        return f"ads/business/imgs/{new_filename}{file_path.suffix}"
    # ----------------------------------------------------------
    title = models.CharField(max_length=100, null=True, blank=True, verbose_name="عنوان")
    # ----------------------------------------------------------
    image = models.ImageField(upload_to=business_image_path, verbose_name="عکس")
    # ----------------------------------------------------------
    business_advertising = models.ForeignKey(to=BusinessAdvertising, on_delete=models.CASCADE, null=True, blank=True, related_name='images', verbose_name="آگهی کسب و کار")

# ==============================================================

barter/models.py
import uuid
import jdatetime
import pathlib
import qrcode
from io import BytesIO
from django.core.files import File
from django.utils.text import slugify
from django.contrib.sites.models import Site
from django.utils import timezone
# from shortuuid.django_fields import ShortUUIDField
from django.db import models
from django.urls import reverse
from account.models import Account


class Category(models.Model):
    CATEGORY_LIST   = (("shop", "فروشگاهی"), ("services", "خدماتی"), ("productive", "تولیدی"))
    title           = models.CharField(max_length=30, verbose_name="نام دسته بندی")
    category_type  = models.CharField(max_length=20, choices=CATEGORY_LIST, verbose_name="نوع کسب و کار", default="shop",)

    def __str__(self):
        return self.title

# ================================================

class Tag(models.Model):
    name = models.CharField(max_length=50)

# ================================================

class StuffImage(models.Model):
    def stuff_image_path(instance, filename):
        file_path = pathlib.Path(filename)
        new_filename = str(uuid.uuid1())
        return f"stuff/imgs/{new_filename}{file_path.suffix}"
    
    title = models.CharField(max_length=40, null=True, blank=True, verbose_name="عنوان")
    image = models.ImageField(max_length=255, upload_to=stuff_image_path, verbose_name="تصویر")
    
# ================================================

class Stuff(models.Model):  
    def stuff_qrcode_path(instance, filename):
        new_filename = str(uuid.uuid1())
        return f"stuff/qrcodes/{new_filename}.png"
    
    STATUS_CHOICES = (
        ('published', 'منتشر شده'),
        ('draft', 'معلق'),
    )
    id    = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # --------------------------------------
    # id = ShortUUIDField(primary_key=True, length=11, max_length=11)
    # --------------------------------------
    title = models.CharField(max_length=120, verbose_name="عنوان")
    # --------------------------------------
    slug = models.SlugField(max_length=200, unique=True)
    # --------------------------------------
    owner = models.ForeignKey(to=Account, null=False, blank=False, on_delete=models.CASCADE, verbose_name="مالک")
    # --------------------------------------
    url_address = models.URLField(max_length=300, null=True, blank=True, verbose_name="آدرس url آگهی") 
    # --------------------------------------
    date_created = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد آگهی")
    # --------------------------------------
    date_published = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ انتشار آگهی")
    # --------------------------------------
    date_updated = models.DateTimeField(auto_now=True, verbose_name="تاریخ آخرین تغییر")
    # --------------------------------------
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, null=True, blank=True, verbose_name="وضعیت انتشار",)
    # --------------------------------------
    summary = models.CharField(max_length=400, null=True, blank=True, verbose_name="خلاصه")
    # --------------------------------------
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name="توضیحات")
    # --------------------------------------
    category = models.ManyToManyField(Category, blank=True)
    # --------------------------------------
    tags = models.ManyToManyField(Tag, blank=True, verbose_name=("تگ"))
    # --------------------------------------
    images = models.ManyToManyField(StuffImage, related_name="stuffs", blank=True, verbose_name="تصاویر")
    # --------------------------------------
    location = models.CharField(max_length=100, verbose_name="موقعیت آگهی")
    # --------------------------------------
    qrcode_image = models.ImageField(max_length=255, upload_to=stuff_qrcode_path, blank=True, null=True)
    # --------------------------------------
    
    class Meta:
        ordering = ("-date_published",)
        default_related_name = "stuffs"
    # --------------------------------------
    
    def get_absolute_url(self):
        return reverse("barter:stuff-detail", kwargs={"stuff_id": self.id, "stuff_slug": self.slug})
    
    # --------------------------------------
    
    def get_update_url(self):
        return reverse("barter:stuff-update", kwargs={"stuff_id": self.id, "stuff_slug": self.slug})
    
    # --------------------------------------
    
    def get_delete_url(self):
        return reverse("barter:stuff-delete", kwargs={"stuff_id": self.id, "stuff_slug": self.slug})
    
    # --------------------------------------
    
    @property
    def JaliliDateCreated(self):
        return jdatetime.date.fromgregorian(
            day=self.date_created.day,
            month=self.date_created.month,
            year=self.date_created.year,
        )

    # --------------------------------------    

    @property
    def JaliliDatePublished(self):
        return jdatetime.date.fromgregorian(
            day=self.date_published.day,
            month=self.date_published.month,
            year=self.date_published.year,
        )
    
    # --------------------------------------
    
    @property
    def JalaliDateUpdated(self):
        return jdatetime.date.fromgregorian(
            day=self.date_updated.day,
            month=self.date_updated.month,
            year=self.date_updated.year,
        )
    
    # --------------------------------------
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        
        # generate url address of barter object
        current_site = Site.objects.get_current()
        self.url_address = str(current_site) + self.get_absolute_url()
                
        # create QRcode based on generated url address
        qr_text = self.url_address
        qr_image = qrcode.make(qr_text, box_size=25)
        qr_image_pil = qr_image.get_image()
        stream = BytesIO()
        qr_image_pil.save(stream, format="PNG")
        file_name = f"{self.slug}-{qr_text}.png"
        self.qrcode_image.save(file_name, File(stream), save=False)
        
        print(f"qr image is : {self.qrcode_image}")
        
        super().save(*args, **kwargs)
    
    # --------------------------------------
    

templates/ads/adv-attach-images.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}ساخت آگهی | تبلیغات{% endblock title %}

{% block content %}
  <h3 class="font-vazir text-center my-6 text-lg font-semibold">حداقل 1 و حداکثر 9 تصویر بارگزاری کنید</h3>
  <form action="" method="post" id="formData" enctype="multipart/form-data" class="flex flex-col items-center">
    {% csrf_token %}
    <input type="file" name="images" id="imagesInput" accept=".jpg,.jpeg,.png,.gif" class="my-4">
    {% if advertise_images|length >= 1  and advertise_images|length <= 9 %}
      <button type="submit" id="register" class="font-vazir bg-blue-600 hover:bg-blue-500 text-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 font-bold py-2 px-4 rounded transition duration-300 disabled:opacity-50" {% if advertise_images|length < 1 %}disabled{% endif %}>ثبت</button>
    {% else %}
      <button type="button" class="bg-gray-300 text-black font-bold py-2 px-4 rounded cursor-not-allowed opacity-50 font-vazir" disabled>حداقل یک تصویر بارگزاری کنید.</button>
    {% endif %}
  </form>

  <!-- Modal for displaying image in full size -->
  <div id="imageModal" class="hidden fixed inset-0 z-50 overflow-auto bg-black bg-opacity-80 flex justify-center items-center">
    <div class="max-w-4xl mx-auto">
      <img id="fullSizeImage" class="max-w-full max-h-full" src="" alt="Full size image">
    </div>
  </div>

  <div id="custom-controls-gallery" class="mt-8 mb-4 mx-10" data-carousel="slide">
    <div id="image-items" class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
      {% for image_obj in advertise_images %}
        <div class="relative group">
          <img class="w-full h-9/12 rounded-lg" src="{{ image_obj.image.url }}" alt="image-{{ image_obj.id }}" data-image-id="{{ image_obj.id }}">
          <button type="button" class="font-vazir absolute top-2 right-2 bg-red-500 text-white font-semibold px-2 py-1 rounded-lg opacity-0 group-hover:opacity-100 transition duration-300 delete-button" data-image-id="{{ image_obj.id }}">
            حذف
          </button>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

{% block custom_js %}
  <script src="{% static 'ads/js/adv-attach-images.js' %}"></script>
{% endblock custom_js %}

templates/ads/adv-create.html
{% extends "base/base.html" %} 
{% block title %}تبلیغات | ساخت آگهی{% endblock title %} 
{% block content %}
<section class="dark:bg-gray-300 font-vazir">
  <div class="lg:w-1/3 mx-auto lg:py-6">
    <div>
      <div class="place-items-center">
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="grid gap-x-8 gap-y-6 sm:grid-cols-2">
            <div>
              <label for="id_title">عنوان آگهی شغلی:</label>
              <div class="mt-2">
                <input
                  maxlength="20"
                  type="text"
                  name="title"
                  id="id_title"
                  autocomplete="given-name"
                  required
                  class="text-center w-full rounded-md py-1.5 placeholder:text-gray-400 sm:text-sm sm:leading-6"
                  placeholder="حداکثر ۲۰ کاراکتر"
                  />
                <div id="title-errors">
                  {% for error in form.title.errors %}
                  <p class="text-red-500 text-xs italic">*{{error}}</p>
                  {% endfor %}
                </div>
              </div>
            </div>
            <div>
              <label for="id_summary"> خلاصه آگهی: </label>
              <div class="mt-2">
                <input
                  maxlength="25"
                  type="text"
                  name="summary"
                  id="id_summary"
                  autocomplete="family-name"
                  required
                  class="text-center w-full rounded-md py-1.5 placeholder:text-gray-400 sm:text-sm sm:leading-6"
                  placeholder="حداکثر ۲۵ کاراکتر"
                  />
                <div id="summary-errors">
                  {% for error in form.summary.errors %}
                  <p class="text-red-500 text-xs italic">*{{error}}</p>
                  {% endfor %}
                </div>
              </div>
            </div>
            <div class="sm:col-span-2">
              <label for="id_description"> توضیحات آگهی: </label>
              <div class="mt-2">{{ form.description }}</div>
              <div id="description-errors">
                {% for error in form.description.errors %}
                <p class="text-red-500 text-xs italic">*{{error}}</p>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="grid gap-x-8 gap-y-6 sm:grid-cols-2">
            <div class="mt-6">
              <label for="region" class="block leading-6"> منطقه: </label>
              <div class="mt-2">
                <select
                  id="region"
                  name="region"
                  autocomplete="region-name"
                  required
                  class="w-full rounded-md py-1.5 text-gray-900 sm:max-w-xs sm:text-sm sm:leading-6"
                  >
                  {% for region in regions %}
                  <option value="{{region.id}}">{{ region }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <div class="mt-6">
              <label for="stuff_status" class="block leading-6">
              وضعیت کالا:
              </label>
              <div class="mt-2">
                <select
                  id="stuff_status"
                  name="stuff_status"
                  class="w-full rounded-md py-1.5 text-gray-900 sm:max-w-xs sm:text-sm sm:leading-6"
                  >
                  {% for status in stuff_statuses %}
                  <option value="{{ status.0 }}">{{ status.1 }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
          </div>
          <div class="mt-6">
            <label for="address">آدرس:</label>
            <div class="mt-2">
              <input
                maxlength="55"
                type="text"
                name="address"
                id="address"
                autocomplete="address"
                required
                class="text-center w-full rounded-md py-1.5 placeholder:text-gray-400 sm:text-sm sm:leading-6"
                placeholder="حداکثر ۵۵ کاراکتر"
                />
              <div id="address-errors">
                {% for error in form.address.errors %}
                <p class="text-red-500 text-xs italic">*{{error}}</p>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="grid gap-x-8 gap-y-6 sm:grid-cols-2">
            <div class="mt-6">
              <label for="categories" class="block leading-6">
              دسته‌بندی:
              </label>
              <div class="mt-2">
                <select
                  id="categories"
                  name="categories"
                  multiple
                  class="w-full rounded-md py-1.5 text-gray-900 sm:max-w-xs sm:text-sm sm:leading-6"
                  >
                  {% for category in categories %}
                  <option value="{{category.id}}">{{ category.title }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <div>
              <div class="mt-6">
                <label for="tags"> تگ‌ها: </label>
                <div class="mt-2">
                  <select
                    id="tags"
                    name="tags"
                    multiple
                    class="w-full rounded-md py-1.5 text-gray-900 sm:max-w-xs sm:text-sm sm:leading-6"
                    >
                    {% for tag in tags %}
                    <option value="{{tag.id}}">{{ tag.name }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
            </div>
          </div>
          <div class="grid gap-x-8 gap-y-6 sm:grid-cols-2">
            <div class="mt-6">
              <label for="price">قیمت (تومان):</label>
              <div class="mt-2">
                <input
                  maxlength="15"
                  type="text"
                  name="price"
                  id="price"
                  autocomplete="price"
                  required
                  class="text-center w-full rounded-md py-1.5 placeholder:text-gray-400 sm:text-sm sm:leading-6"
                  placeholder="حداکثر ۱۵ کاراکتر"
                  />
                <div id="price-errors">
                  {% for error in form.price.errors %}
                  <p class="text-red-500 text-xs italic">*{{error}}</p>
                  {% endfor %}
                </div>
              </div>
            </div>
            <div class="mt-6">
              <label for="status" class="block leading-6">
              وضعیت انتشار آگهی:
              </label>
              <div class="mt-2">
                <select
                  id="status"
                  name="status"
                  required
                  class="w-full rounded-md py-1.5 text-gray-900 sm:max-w-xs sm:text-sm sm:leading-6"
                  >
                  <option value="published">انتشار</option>
                  <option value="draft">پیش نویس</option>
                </select>
              </div>
            </div>
          </div>
      <button
        class="mt-4 mb-2 bg-blue-600 hover:bg-blue-500 text-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 w-full py-1.5 rounded-md"
        role="group"
        >
      ثبت آگهی
      </button>
      </form>
    </div>
  </div>
  </div>
</section>
{% endblock content %} 
{% block custom_js %}
<script></script>
{% endblock custom_js %}

templates/ads/adv-list.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}دیجی خدمت | تبلیغات{% endblock title %}

{% block custom_assets %}

{% endblock custom_assets %}

{% block content %}
<div class="relative flex min-h-screen flex-col justify-center overflow-hidden py-6 sm:py-12 font-vazir">
  <div class="min-h-28 ">
    <div class="max-w-screen-lg mx-auto py-4">

      <div class="border-2 bg-blue-700 text-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 rounded-md p-4">
        <h2 class="font-bold text-center text-6xl">
          تبلیغات
        </h2>
        <h2 class="text-3xl mt-2 text-center font-semibold">در این صفحه میتوانید آگهی های خود را درج کنید یا آگهی دیگران
          را ببینید.
        </h2>
        <p class="text-center mt-4">- صفحه آگهی‌های تبلیغاتی کسب‌وکارها و کالاها -</p>
      </div>

      <!-- start adv items -->
      <div 
        id="ads-list"
        class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 mt-6"
      >
        {% for adv in ads %}
          <div
            class="adv-item"
            id="{{ adv.id }}"
            data-slug="{{ adv.slug }}"
          >
            <a href="{{ adv.get_absolute_url }}">
              <div class="bg-blue-600 hover:bg-blue-500 text-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 group-hover:opacity-75 lg:aspect-none w-full shadow rounded-lg overflow-hidden">
                <img src="{{ adv.images.first.image.url }}" class="object-cover h-40 w-full" alt="">
                <div class="p-6 flex flex-col flex-1">
                  <h3 class="mt-3 mb-2 font-bold text-lg">
                    {{ adv.title }}
                  </h3>
                  <h2 class="text-xs  mb-3">{{ adv.summary }}</h2>
                  <div class="flex gap-4 items-center mt-auto pt-4 border-t border-slate-950">
                    <span style="text-align: right" class="block  font-semibold text-sm mx-2">{{ adv.date_published | to_Jdate }}</span>
                    <span class="flex gap-1  text-sm">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="currentColor" class="w-4 h-4">
                        <path stroke-linecap="round" stroke-linejoin="round"
                          d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                      </svg>
                      <span class="adv-item-view">{{ adv.views }} بازدید</span>
                    </span>
                  </div>
                </div>
              </div>
            </a>
          </div>
        {% endfor %}
        <!-- end adv items -->

        <!-- start pagination -->
        {% if ads.has_other_pages %}
          <div class="flex justify-center mt-5">
            <ul class="flex">
              {% if ads.has_previous %}
                <li class="mr-1">
                  <a href="?page={{ ads.previous_page_number }}"
                    class="px-3 py-2 bg-blue-500 text-white rounded-l-md hover:bg-blue-600">&laquo;</a>
                </li>
              {% else %}
                <li class="mr-1 opacity-50 cursor-not-allowed">
                  <span class="px-3 py-2 bg-blue-300 text-white rounded-l-md">&laquo;</span>
                </li>
              {% endif %}

              {% for i in ads.paginator.page_range %}
                {% if ads.number == i %}
                  <li class="mr-1">
                    <span class="px-3 py-2 bg-blue-700 text-white">{{ i }}</span>
                  </li>
                {% else %}
                  <li class="mr-1">
                    <a href="?page={{ i }}" class="px-3 py-2 bg-blue-500 text-white hover:bg-blue-600">{{ i }}</a>
                  </li>
                {% endif %}
              {% endfor %}

              {% if ads.has_next %}
                <li class="mr-1">
                  <a href="?page={{ ads.next_page_number }}"
                    class="px-3 py-2 bg-blue-500 text-white rounded-r-md hover:bg-blue-600">&raquo;</a>
                </li>
              {% else %}
                <li class="mr-1 opacity-50 cursor-not-allowed">
                  <span class="px-3 py-2 bg-blue-300 text-white rounded-r-md">&raquo;</span>
                </li>
              {% endif %}
            </ul>
          </div>
        {% endif %}
        <!-- end pagination -->
      </div>
    </div>
  </div>
</div>
{% endblock content %}


{% block custom_js %} 
  <script src="{% static 'ads/js/adv-list.js' %}"></script>
{% endblock custom_js %}